### ISSUE TITLE
Verify that security bump of Mongoose version does not break observability platform

### ISSUE THREAD

**Issue by i5haan** [zgeorge2/RAD-Squared#5]
There is a deprecation warning which we need to fix. As below.

(node:7897) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**Comment by zgeorge2** [comment]
Is this a testing exercise or something more? 
There have also been a couple of vulnerability fixes that need similar validation.

**Comment by i5haan** [comment]
It is one of those vulnerability fixes, basically the mongoose one. Mongoose is an explicitly mentioned dependency used to connect to mongoDB server. The dependabot just bumped it to LTS, which will just require some basic spot testing since our setup with the database is not very complex.

**Comment by zgeorge2** [comment]
Sounds good. Go for it. If you notice there are a couple of other vulnerability fixes too that bumped up other components.

**Comment by i5haan** [comment]
Yeah, I see two of them, one of which is mongoose. The other is a sub dependency(acorn), which I don't think should cause problems otherwise there would have been a prompt to update the actual parent dependency as well.
 
https://github.com/zgeorge2/RAD-Squared/commit/15e979fd77539256f0b92a5e38d84975846a566f

https://github.com/zgeorge2/RAD-Squared/commit/845b1282d7591f9c783651001c1a48ebd4666e4c
